### ISSUE TITLE
MPURI from expired or deleted images

### ISSUE THREAD

**Issue by arax** [EGI-FCTF/oneacct_export#1]
When an image expires or is deleted while a particular VM instance is still running, `ImageId` reported to APEL changes from `MPURI` to `OCCI mixin identifier`. This needs to be fixed.

### Proposed solution
1. Copy `MPURI` to VM instance metadata (out of scope for `oneacct-export`)
2. Read `MPURI` from VM instance metadata first, fall back to other sources if necessary

__Solution requires changes in OpenNebula configuration (inherited image attributes) or in rOCCI-server (copying MPURI manually)!__

**Comment by sustr4** [comment]
Shouldn't we start by confirming that identifying VMs by ImageId is correct? Perhaps this should be fixed lower down the chain.

**Comment by arax** [comment]
It should be fixed in APEL ... but it doesn't change the fact that reporting one image under two different `ImageId`s (just because it was deleted or expired) is a bug.

**Comment by sustr4** [comment]
There you're right.

**Comment by jcgordon** [comment]
We are reviewing how APEL handles this. We identify VMs by the VMUUID which includes the original ImageID. This doesn't change when the image expires but in the case I highlighted we have the same VM published with a different VMUUID - a difference of two seconds in starttime.

**Comment by arax** [comment]
@jcgordon The part about changing `ImageId`s is our problem (bug in `oneacct-export`). We can fix that.

If the same VM was reported with two slightly different start times, that is probably a bug in OpenNebula. If that's the case, there is not much we can do. Aside from reporting a bug to OpenNebula devs.

**Comment by arax** [comment]
@jcgordon Duplicate entries with slightly different start times have been identified as side-effects of the migration from `opennebula-cloudacc` to `oneacct-export`. Older (conflicting) entries can be safely removed.

**Comment by jcgordon** [comment]
I will attempt to trace these by looking for multiple occurrences of the same MachineName. I suspect they will all go away anyway in the general cleanup.

**Comment by arax** [comment]
@Misenko Every `TEMPLATE/DISK` element will from now on contain the following attributes inherited from `IMAGE`:
~~~
VMCATCHER_EVENT_AD_MPURI
VMCATCHER_EVENT_DC_IDENTIFIER
VMCATCHER_EVENT_HV_VERSION
VMCATCHER_EVENT_IL_DC_IDENTIFIER
VMCATCHER_EVENT_SL_CHECKSUM_SHA512
~~~
`TEMPLATE/DISK/VMCATCHER_EVENT_AD_MPURI	` is the one we need (first in the fallback chain).

**Comment by arax** [comment]
(waiting for merge)

**Comment by arax** [comment]
Ref. #3
