### ISSUE TITLE
Add disk size to APEL output

### ISSUE THREAD

**Issue by Misenko** [EGI-FCTF/oneacct_export#2]
Information from `TEMPLATE/DISK/SIZE` should be summed for all the disks in template and available in APEL's `Disk` field.

**Comment by arax** [comment]
`TEMPLATE/DISK/SIZE` is in MBs, APEL's `Disk` is in GBs.

**Comment by arax** [comment]
(waiting for merge)

**Comment by arax** [comment]
Ref. #3
